Repository dev-ujed/adminujed, pull requests merged in 2025-03, with the labels that each got.

#2 front del login lista
  admin/settings.py
  package-lock.json
  package.json
  public/views.py
  requirements.txt
  resources/css/7-components/inicio.scss
  resources/js/public/components/Inicio.vue
  templates/_estructure/master.html
Labels: FrontEnd

#5 backend del login
  .gitignore
  admin/settings.py
  package-lock.json
  package.json
  public/migrations/0001_initial.py
  public/models.py
  public/serializers.py
  public/urls.py
  public/views.py
  requirements.txt
  resources/js/main.js
  resources/js/public/components/Inicio.vue
  static/img/Icon mail.png
  static/img/Icon tabler key.png
  static/img/LogoUJEDvertical.png
  static/img/fondo-login.png
  templates/public/home.html
Labels: BackEnd

#8 Estructura proyecto
  admin/settings.py
  admin/urls.py
  administracion/__init__.py
  administracion/admin.py
  administracion/apps.py
  administracion/migrations/__init__.py
  administracion/models.py
  administracion/tests.py
  administracion/urls.py
  administracion/views/profesor.py
  administracion/views/unidad.py
  administracion/views/views.py
  public/urls.py
  public/views.py
  resources/js/admin/components/dashboard/Navbar.vue
  resources/js/public/components/Inicio.vue
  templates/admin/home.html
  templates/admin/master.html
  templates/admin/profesor/index.html
  templates/admin/unidad/index.html
Labels: FrontEnd, BackEnd

#12 mejoras en la tabla de maestros
  resources/css/7-components/_pagination.scss
  resources/css/7-components/_profesores.scss
  resources/js/admin/components/profesor/Profesores.vue
  static/img/icon-next.png
  static/img/icon-prev.png
Labels: FrontEnd

#13 pantalla de unidades creada
  resources/css/7-components/_unidades.scss
  resources/css/main.scss
  resources/js/admin/components/unidades/Unidades.vue
  resources/js/main.js
  static/img/filtro-icon.png
  templates/admin/unidad/index.html
Labels: FrontEnd

#15 inicio desarrollo de programas
  administracion/urls.py
  administracion/views/unidad.py
  resources/css/7-components/_dashboard-panel.scss
  resources/css/7-components/detalles_unidades.scss
  resources/css/main.scss
  resources/js/admin/components/unidades/Detalles.vue
  resources/js/admin/components/unidades/Unidades.vue
  resources/js/main.js
  templates/admin/unidad/detalles.html
Labels: FrontEnd, BackEnd

#18 mostrar unidades desde la BD
  administracion/models.py
  administracion/urls.py
  administracion/views/unidad.py
  resources/css/7-components/_dashboard-menu-admin.scss
  resources/css/7-components/_unidades.scss
  resources/css/7-components/detalles_unidades.scss
  resources/js/admin/components/unidades/Detalles.vue
  resources/js/admin/components/unidades/Unidades.vue
  templates/admin/unidad/detalles.html
Labels: FrontEnd, BackEnd

#19 mostrar listado de maestros
  administracion/models.py
  administracion/urls.py
  administracion/views/profesor.py
  resources/css/7-components/_profesores.scss
  resources/js/admin/components/profesor/Profesores.vue
  resources/js/admin/components/unidades/Unidades.vue
  resources/js/public/components/Inicio.vue
Labels: FrontEnd, BackEnd
